/**
 * Shared application-level TypeScript types.
 *
 * These are NOT auto-generated by Prisma — they represent the shapes used
 * in component props, API responses, and client-side logic.
 */

// ---------------------------------------------------------------------------
// Auth / Session
// ---------------------------------------------------------------------------

/** User object attached to the NextAuth session. */
export interface SessionUser {
  id: string;
  email: string;
  name: string | null;
  role: 'AUTHOR' | 'ADMIN' | 'READER';
  /** Linked author profile ID (null for non-author users). */
  authorId: string | null;
}

// ---------------------------------------------------------------------------
// API responses
// ---------------------------------------------------------------------------

/**
 * Standardised JSON envelope for all API routes.
 *
 * @typeParam T - The shape of the `data` payload on success.
 */
export interface APIResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

/**
 * Paginated list response used by all listing endpoints.
 *
 * @typeParam T - The shape of each item in the `data` array.
 */
export interface PaginatedResponse<T = unknown> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

// ---------------------------------------------------------------------------
// Domain enums / status types (mirrors Prisma enums for client-side use)
// ---------------------------------------------------------------------------

/** Royalty payment status for a given period. */
export type RoyaltyStatus = 'fully_paid' | 'pending' | 'overdue';

/**
 * Book lifecycle status — mirrors Prisma BookStatus enum.
 */
export type BookStatus =
  | 'MANUSCRIPT_RECEIVED'
  | 'EDITING'
  | 'COVER_DESIGN'
  | 'TYPESETTING'
  | 'PROOFREADING'
  | 'ISBN_ASSIGNMENT'
  | 'PRINTING'
  | 'DISTRIBUTION_SETUP'
  | 'PUBLISHED'
  | 'WRITING_CHALLENGE_IN_PROGRESS';

/** Order lifecycle status — mirrors Prisma OrderStatus enum. */
export type OrderStatusType =
  | 'PENDING'
  | 'CONFIRMED'
  | 'PROCESSING'
  | 'SHIPPED'
  | 'DELIVERED'
  | 'CANCELLED'
  | 'REFUNDED';

/** Support ticket status — mirrors Prisma TicketStatus enum. */
export type TicketStatusType = 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED';

// ---------------------------------------------------------------------------
// Utility generics
// ---------------------------------------------------------------------------

/** Make selected keys of T required while keeping the rest unchanged. */
export type WithRequired<T, K extends keyof T> = T & { [P in K]-?: T[P] };

/** Pick only the keys whose values extend V. */
export type PickByValue<T, V> = Pick<T, { [K in keyof T]: T[K] extends V ? K : never }[keyof T]>;
